### ISSUE TITLE
Typo in button.xml

### ISSUE THREAD

**Issue by matejmosko** [kodi-game/game.libretro.pcsx-rearmed#11]
In file resources/button.xml I have probably found a typo in these lines:
`<controller id="game.controller.ps.gamepad" type="RETOR_DEVICE_JOYPAD">`
and
`<controller id="game.controller.ps.dualanalog" type="RETOR_DEVICE_ANALOG">`

It should probably be 
`<controller id="game.controller.ps.gamepad" type="RETRO_DEVICE_JOYPAD">`
and
`<controller id="game.controller.ps.dualanalog" type="RETRO_DEVICE_ANALOG">`

I have checked in other cores and it is definitely RETRO there. I don't know whether this means something for the buttonmap itself, but it seems so.

**Comment by garbear** [comment]
Thanks for catching. I also pushed fixes to some other emulators: Beetle PSX, Rustation, Yabause and PPSSPP
