### ISSUE TITLE
Configuration errors in log

### ISSUE THREAD

**Issue by KOPRajs** [kodi-game/game.libretro.pcsx-rearmed#15]
## Bug report
While debugging another problem I noticed these:
ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): Setting pcsx_rearmed_pad1type: invalid value "standard" (values are: Pad 1 Type; default|none|standard|analog|dualshock|negcon)
ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): Setting pcsx_rearmed_vibration: invalid value "disabled" (values are: Enable Vibration; enabled|disabled)

Kodi 18.0 RC1
PCSX reARMed 22.0.0.1.111

P.S. However changing the Pad 1 type actually has effect in games so the setting seems to work.

**Comment by garbear** [comment]
Looks like a typo in PCSX-rearmed source code. Can you find it?

**Comment by KOPRajs** [comment]
I don't see this in the log anymore, let's close this one.
