### ISSUE TITLE
Version 22.0.0.9.1 crashes Kodi

### ISSUE THREAD

**Issue by KOPRajs** [kodi-game/game.libretro.pcsx-rearmed#16]
### Describe the bug
Here is a clear and concise description of what the problem is:
After the update to 22.0.0.9.1 this core doesn't work anymore. It shows black screen for a while and then crashes Kodi. Reverting back to 22.0.0.6.1 makes it work again. I've tested it on Windows 10 x64, LibreELEC x64 and CoreELEC Amlogic-ng. All platforms seems to be affected.

Possibly related to the new dynarec and related changes in the Makefile.libretro?
https://www.libretro.com/index.php/pcsx-rearmed-now-has-dynarec-support-across-multiple-platforms/
https://github.com/libretro/pcsx_rearmed/commit/3d96277d011b4d683d682740eed61b1113a613b1

## RetroArch Behavior
Here is a clear and concise description of what happens in RetroArch with the same core/game:

### To Reproduce

1. Run any PSX game using the PCSX-reARMed
2. Kodi crashes

### Debuglog

The debuglog can be found here:
https://pastebin.com/P5ybh8Z6

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

Operating system version/name: Windows 10 x64, LibreELEC x64 and CoreELEC Amlogic-ng

Kodi version: 18.x

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by KOPRajs** [comment]
UPDATE: I believe there are actually 3 separate issues on the 3 platforms I've tested:

1. The first one affects only the Windows x64 build. It is caused by the fact that the x64 build is now using the new lightrec dynarec, which needs the real BIOS file to be present. If there is no BIOS file, it crashes. This bug seems to be already fixed in upstream: https://github.com/libretro/pcsx_rearmed/commit/44747c73cf572febe81ff687c81548ce5b5de493
When the BIOS file is present it works in the current Windows build.

2. Second issue is in the LibreELEC build script. It needs to be updated to reflect the new DYNAREC=ari64 build option instead of the old USE_DYNAREC=1 for ARM and DYNAREC=lightrec for x64.
https://github.com/LibreELEC/LibreELEC.tv/blob/libreelec-9.2/packages/emulation/libretro-pcsx-rearmed/package.mk
Look here for the changes in the Makefile: https://github.com/libretro/pcsx_rearmed/commit/3d96277d011b4d683d682740eed61b1113a613b1
Without this update the LibreELEC ARM build will suffer a performance loss due to not using the dynarec anymore.

3. The third issue is causing the actual crash in the current LibreELEC builds. This one also seems to be already fixed in upstream:
https://github.com/libretro/pcsx_rearmed/commit/1d579bf754d091727cb9b2ae0e6933b256739b59

**Comment by garbear** [comment]
Thanks for the report. I'll update the core when I get a chance, which should fix 1. and 3.

**Comment by KOPRajs** [comment]
A little suggestion on improvement regarding the new version:
There are options in the core that allow for workaround bugs in some games and make them playable. These options needs to be changed on the fly and on per game basis. It might be useful to move these options in the core settings page to the top so they are easily accessible from the in-game menu.

I'd suggest an order like this, but feel free to modify it, I'm not 100% familiar with all of them:
pcsx_rearmed_nosmccheck
pcsx_rearmed_nogteflags
pcsx_rearmed_gteregsunneeded
pcsx_rearmed_idiablofix
pcsx_rearmed_inuyasha_fix
pcsx_rearmed_pe2_fix
pcsx_rearmed_psxclock

**Comment by garbear** [comment]
The order is determined by the core: https://github.com/libretro/pcsx_rearmed/blob/master/frontend/libretro_core_options.h

I don't think we support options being changed on the fly. Currently the [settings.xml](https://github.com/kodi-game/game.libretro.pcsx-rearmed/blob/master/game.libretro.pcsx-rearmed/resources/settings.xml) file is generated off-line.

**Comment by KOPRajs** [comment]
But the order in the linked header is different from what we've got in the current version. The order in the libretro_core_options.h is actually close to what I've suggested (except that the game specific options are in the bottom, which is also fine).

As for the on the fly options changes support, maybe it wasn't meant that way, but it definitely works in the current version.

**Comment by KOPRajs** [comment]
You can download the reordered settings.xml from here:
http://koprajs.mx-net.cz/settings.xml

I did no other changes but reordered the options according to the libretro_core_options.h.

**Comment by KOPRajs** [comment]
The crash should be resolved and the settings are discussed separately in #19. Let's close this one.
