### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by KOPRajs** [kodi-game/game.libretro.pcsx-rearmed#19]
### Describe the bug
Here is a clear and concise description of what the problem is:

The settings.xml is outdated and is missing important features.

1. The current version is missing some important features (e.g. pcsx_rearmed_nosmccheck which is needed for some games to run).

2. It doesn't respect the built-in GPU plugin. There are GPU specific options which should be available for specific builds only. When the add-on is built with the NEON GPU it should provide NEON GPU specific settings (now missing), otherwise the PEOPS GPU specific settings should be included (now always available even if the add-on does not have PEOPS GPU built-in).

3. The order of the options is chaotic and doesn't respect the core's default order.

While 1 and 3 can be fixed easily, I'm not sure what would be the best solution for 2.

1. The quick and easy solution would be to include settings for all GPU plugins. Some of them would do nothing but at least all of them would be available. Currently, there are all the PEOPS settings available in the NEON GPU builds, but they do nothing, so it wouldn't be worse than it is. In such case we can give the options some kind of prefix like [NEON] or [P.E.O.P.S.] so the user at least know which settings are useless for him.

2. I'm not sure if there is nice way how to do a kind of "ifdef" in the settings.xml.

3. We can even build 2 separate add-ons, one with NEON and the other with PEOPS. It would be one more core, but it would give users the ability to choose the GPU plugin, so even the PEOPS could be used on ARM in the future etc.

We have solved 1 and 3 in CoreELEC some time ago, so you can use it as a reference:
https://github.com/CoreELEC/CoreELEC/tree/coreelec-9.2/packages/mediacenter/kodi-binary-addons/game.libretro.pcsx-rearmed/sources/game.libretro.pcsx-rearmed/resources
In CoreELEC it is always built with NEON, so it has only the NEON options included. In case of the solution number 1 you just need to add the PEOPS options to the CoreELEC version of the setting.xml. And also add the prefixes to strings.po.

## RetroArch Behavior
Here is a clear and concise description of what happens in RetroArch with the same core/game:

Shows correct settings according to the built-in GPU plugin.

### To Reproduce

1. Open the add-on settings

### Debuglog

The debuglog can be found here:
No log needed.

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [X] Android
 - [X] iOS
 - [X] Linux
 - [X] OSX
 - [X] Raspberri-Pi
 - [X] Windows
 - [X] Windows UWP

Operating system version/name: LibreELEC

Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

**Comment by garbear** [comment]
The settings should be current as of 15 days ago: https://github.com/kodi-game/game.libretro.pcsx-rearmed/commit/2faf2bdbbb3268c60fe2dd7c77097afc25a0770d#diff-acf14716c5e5d27fe87d684609d0a87e22f6cd7647999e010c00448b1773fe8d

Have there been changes since then? I ran the updater script last night and it detected no changes.

**Comment by KOPRajs** [comment]
Hmm, I can see that it is updated 8 hours ago, but it is still missing options.

1. General settings
- pcsx_rearmed_psxclock
- pcsx_rearmed_nogteflags
- pcsx_rearmed_nosmccheck

2. Gamepad types seems to be gone
- pcsx_rearmed_pad1type
- pcsx_rearmed_pad2type
- ...

3. I am missing the NEON GPU settings
- pcsx_rearmed_neon_interlace_enable
- pcsx_rearmed_neon_enhancement_enable
- pcsx_rearmed_neon_enhancement_no_main

The missing options are not new, they are missing for at least a year now. They seem to be supported by the core itself, just not accessible from Kodi UI.

I am using some of these on my Leia (CoreELEC 9.2) build. Especially pcsx_rearmed_nosmccheck needs to be changed on the fly from the in game menu for some games to work, which is why the order of the options matter to me. Also pcsx_rearmed_neon_enhancement_enable is very useful.

**Comment by garbear** [comment]
My guess is that these options are enabled when a game is run, not at init time. We only check options at init time currently (we'd need a game to run for every system otherwise). Or perhaps settings are enabled conditionally in a way we don't check. All answers are revealed in this file: https://github.com/libretro/pcsx_rearmed/blob/master/frontend/libretro.c. When I have time I'll look into it.

**Comment by KOPRajs** [comment]
Unfortunately I don't know the mechanism behind the update process. Are the so called "game scripts" publicly available?

All the options including their values and labels are defined in the header: https://github.com/libretro/pcsx_rearmed/blob/master/frontend/libretro_core_options.h

Some of them are defined conditionally during build time, which seems to be the case for the missing ones. We are missing those under NEW_DYNAREC and GPU_NEON (I don't think we need GPU_UNAI for now).

Also please note that they are defined in the desired order which would be nice to keep for the add-on.

**Comment by garbear** [comment]
Settings that are dependent on compile-time variables are a problem, because we generate settings on x86_64 hardware. We might have to add missing settings by hand, though I'm not sure how we'd handle future updates. What if we patch the source to expose all settings unconditionally? Then we just have to maintain code, a different problem than maintaining data that has to match code.

It shouldn't be a problem if we expose NEON settings on non-NEON hardware, as long as the core safely ignores inapplicable settings. I think Kodi might have a way to conditionally hide settings, but this would have to be done by hand, as the libretro options API doesn't expose any way to determine conditions.

**Comment by KOPRajs** [comment]
I don't know what exactly needs to be changed to expose all the settings since I still don't know the mechanism which generates them.

Currently I'm running a NEON GPU build and have P.E.O.P.S. options available and it seems to work, but I guess it depends on the modification needed to "expose" all settings.

**Comment by garbear** [comment]
How about this? https://github.com/kodi-game/game.libretro.pcsx-rearmed/pull/20

**Comment by KOPRajs** [comment]
Regarding the order of the settings:
It seems we are currently reordering the original options order from libretro to alphabet order. I don't think it is a good idea. The order in the libretro makes sense as related options are kept together.

It seems it is done on line 329 in this file: https://github.com/kodi-game/kodi-game-scripting/blob/master/kodi_game_scripting/process_game_addons.py

I'd suggest to simply remove the "sorted" function and keep the libretro default order.

**Comment by garbear** [comment]
Interesting, the re-ordering must be happening in the Python script. I'll see if I can find out where it's being reordered.

**Comment by garbear** [comment]
Looks like removing `sorted` fixes it, opened a PR: https://github.com/kodi-game/kodi-game-scripting/pull/86

**Comment by garbear** [comment]
Let me know how the updated PR looks: https://github.com/kodi-game/game.libretro.pcsx-rearmed/pull/21

**Comment by garbear** [comment]
@KOPRajs thanks for helping me track this down! I don't have much time or free concentration (and you probably noticed I skip over some words) but with summer approaching and the GSoC project I wanna pay down some technical debt.

One step left... let's bump the version and see the results after they make it through CI to your box!

**Comment by KOPRajs** [comment]
Thanks. Now let's merge all the other great stuff like Savestate manager and GL shaders and also let's finish the support for GL cores :-)

Well, while this should work for now, we should think of a better solution in the long term. There might be other addons missing options as well. Would it be possible to generate settings.xml during the addon build process?

**Comment by garbear** [comment]
> Would it be possible to generate settings.xml during the addon build process?

Surprisingly, we actually generate settings.xml on the machine when the addon is started without settings (and maybe even with, I forget): https://github.com/kodi-game/game.libretro/blob/Matrix/src/settings/SettingsGenerator.cpp

However, the code there is probably out of date, using the old style settings format, as I didn't maintain it after kodi-game-scripting got settings generation. But that's how I generated the settings for https://github.com/kodi-game/game.libretro.mrboom/pull/12.

Is something like this what you have in mind? Unfortunately I don't think it'll work "on-line", because we can't always write to the add-on directory.

**Comment by KOPRajs** [comment]
Wow, didn't know about that possibility. I'm not sure what is the best solution for this, however if we want to generate settings from the compiled library and not from the header file itself, then we should do that on the target machine. If we cannot always write to the addon directory from libretro, then the only possibility I see is during the addon build (after the library is compiled and before the addon is packed to the zip).

**Comment by garbear** [comment]
>  if we want to generate settings from the compiled library and not from the header file

We do this. We compile the library (header gets slurped in) and then dyload it with Python ctypes. But only on the machine that kodi-game-scripting is run on, which is an Azure instance of x86_64. I can't cores to compile consistently on any of my desktops, it's really picky about dependencies. running the script on macOS would be a nightmare.

**Comment by KOPRajs** [comment]
I don't think the problem is that it is running on the x86_64 but that the python script with ctypes is only run once and it generates a static settings.xml for all platforms.

The idea is like this:
1. kodi-game-scripting is run to update the addons
- place the settings.xml template instead of the generated settings.xml to the addon sources
- add a python script for generating settings.xml to the sources
- modify the cmake file to run the script after the build

2. the addon build is run (doesn't matter on what platform the build is run)
- the library is cross-compiled for the target platform
- the python ctypes script is called and the settings.xml is generated
- both the compiled library and the generated setting.xml are added to the addon.zip

The thing is if we can simply add this extra step to the standard Kodi addon build process by adding to the addon cmake.txt. I don't know the Kodi addon build process good enough to tell. Anyway it wouldn't be a simple change but relatively complex project.

**Comment by garbear** [comment]
I don't think this will work for cross-compiling :( ctypes loads the shared library into the current binary executable process, and the architecture of the shared lib must match the process that tries to load it. In this case the Python interpreter. So when cross-compiling, we'd have to run Python, and an OS to support it, in an emulator.

**Comment by KOPRajs** [comment]
Sorry, I should have looked how ctypes works, in that case we are doomed :-)

**Comment by garbear** [comment]
I think the approach we take for missing settings (like if settings are only presented when a game is loaded) is to patch them in, put them behind an "Advanced" label in the GUI, and have cores safely ignore settings that don't apply. In the future, we could aggregate which settings are platform-specific and generate a settings.xml where Kodi hides settings conditionally.

Far too much work for now, but can you open issues for other missing settings you find? And close this one if all needed settings now appear.

**Comment by KOPRajs** [comment]
In theory we could throw away the settings.xml completely and only display settings generated from the library in runtime (game.libretro would have to deal with that) but we would loose the ability to change settings without the core being loaded.

**Comment by garbear** [comment]
Right, Kodi's binary add-on API has something to do with settings, but from what I recall it was very limited, unsafe, doesn't let you change any without loading the core, no cores besides a single PVR add-on used it, and it probably doesn't work today.

I only have time these days for quick, simple fixes but it's fun to brainstorm what a proper solution would look like :) at the extreme end we could do what I did with button maps, same case where libretro API was insufficient so I went through all 80 cores at the time, created buttonmaps by hand, and build a huge, elaborate system that pulls input data from multiple sources to give you a decent change of input working out of the box.

Maybe Kodi needs to way to show extra settings at runtime like libretro, so you can configure base settings outside of a game, and game-specific ones inside each game. I think an extension to our settings system might be the only correct fix, but is a big project and honestly probably not worth the large amount of work.

Open to any and all ideas.

**Comment by KOPRajs** [comment]
I agree that the current solution seems good enough for now. There are other portions of Retroplayer where the time investment would be more beneficial.

To the brainstorming what proper solution would look like:

We should probably look how Retroarch do this. Does it have something similar to the settings.xml or does it rely purely on reading available options from the core library in runtime?

If the latter is the case then we can build on top of the binary addon API you mention. Since it would be a long term goal, we can enhance the API if it currently does not provide everything needed. The Kodi would have to load the library when user opens the settings dialog even without running the game.
