### ISSUE TITLE
PCSX games renders just black screen

### ISSUE THREAD

**Issue by matejmosko** [kodi-game/game.libretro.pcsx-rearmed#9]
I have been trying to make playstation games run on libreelec (RPi3) kodi, but with no success. First I was struggling with cue files not recognized untill I finally found out that I needed to prevent this file extension in advancedsettings.xml

```xml
<advancedsettings>
  <videoextensions>
    <remove>.bin|.img|.iso|.zip</remove>
  </videoextensions>
  <musicextensions>
    <remove>.cue|.zip</remove>
  </musicextensions>
  <pictureextensions>
    <remove>.zip</remove>
  </pictureextensions>
</advancedsettings>
```

Now I was able to choose pcsx as emulator. But the only thing I see is black color. I can get to retroplayer menu. Refresh / Restart (I have it translated, so I don't know the exact word) and Exit does the same - freezes Kodi UI. I still can connect to RPi via SSH. But only rebooting gets me back to Libreelec.

[Logs are here](http://paste.ubuntu.com/26147128/)

**Comment by garbear** [comment]
Possibly related: https://forum.kodi.tv/showthread.php?tid=311172&pid=2693895#pid2693895

**Comment by matejmosko** [comment]
After cores and game.libretro update on Milhouse #0225 build the controls in PCSX games are still not working. On first run, the game starts with random graphical artifacts (it varies across different games). I have to stop the game and start it again. Every game looks fine on second run.

However, when I get to the game menu, the game doesn't respond to controller. This is [the log](http://ix.io/PWG) In log I have tried three different games with same result. The part I consider interesting is this:

```log
21:46:03.547 T:1941737488   ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): Buttonmap version required, expected version 2 (min=2)
21:46:03.547 T:1941737488   DEBUG: AddOnLog: Sony - PlayStation (PCSX ReARMed): Loading controller topology "/storage/.kodi/addons/game.libretro.pcsx-rearmed/resources/topology.xml"
21:46:03.548 T:1941737488   ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): Failed to load controller topology: Error reading end tag. (line 55)
```

**Comment by garbear** [comment]
Yes. Thank you for posting a debug log. It says exactly what the problem is: [this line](https://github.com/kodi-game/game.libretro.pcsx-rearmed/blob/master/game.libretro.pcsx-rearmed/resources/topology.xml#L54). Submitting a fix now.

**Comment by matejmosko** [comment]
Meanwhile I have found out, the </port> tag is missing exactly three times in the file. Not just on line 55. Two previous <port> tags aren't closed as well.

**Comment by matejmosko** [comment]
I have manually added `</port>` tags to my topology.xml. The error is gone, but controls still not working. This is the [new log](http://ix.io/PXf).

Thanks for your hard work.

**Comment by garbear** [comment]
The error is:
```
ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): Buttonmap version required, expected version 2 (min=2)
```

Pretty clear. Version isn't specified.

https://github.com/kodi-game/game.libretro.pcsx-rearmed/pull/12 updated with the fix.

**Comment by matejmosko** [comment]
I have added all the changes you made in #12 into my kodi, but controls still not working.
[This is the log](http://ix.io/PYo)
To make sure everything is setup right, I have re-setup all the PS controllers and [logged it as well](http://ix.io/PYA) with the games still not recognizing controls.

**Comment by garbear** [comment]
I've put effort into making the error logging verbose enough to track down. Now the error is:
```
ERROR: AddOnLog: Sony - PlayStation (PCSX ReARMed): <feature> tag has invalid "mapto" attribute: "RETRO_RUMBLE_STRONG"
```

Fix submitted: https://github.com/kodi-game/game.libretro/pull/35

**Comment by matejmosko** [comment]
Gotcha! I have deleted those two features from buttonmap.xml and the controls are working now. You are the king. Thanks.

**Comment by garbear** [comment]
Can this be closed?

**Comment by matejmosko** [comment]
Yes

**Comment by matejmosko** [comment]
Yes.
